services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: twipie_app
    working_dir: /var/www/html
    ports:
      - "80:80"
      - "5173:5173"
    environment:
      APP_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    volumes:
      - ./:/var/www/html
    networks:
      - twipie
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: twipie_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - twipie

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      device: ./docker/volumes/dbdata
      o: bind


networks:
  twipie:
    driver: bridge
