services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: twipie_app
    working_dir: /var/www/html
    environment:
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      ASSET_URL: ${ASSET_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel
    depends_on:
      - db

  webserver:
    build:
      context: .
      dockerfile: server.Dockerfile
      target: production
    container_name: twipie_webserver
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: twipie_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - prod_dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  prod_dbdata:
    driver: local
    driver_opts:
      type: none
      device: /mnt/docker-volumes/dbdata
      o: bind

networks:
  laravel:
    driver: bridge
