services:
  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ${DB_VOLUME:-dbdata}:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:
  prod_dbdata:
    driver: local
    driver_opts:
      type: none
      device: /mnt/docker-volumes/dbdata
      o: bind
