services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    depends_on:
      - db

  npm:
    image: node:20-alpine
    container_name: npm_dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: ["npm", "run", "dev"]
    networks:
      - laravel
    depends_on:
      - app
    ports:
      - "5173:5173"

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
