services:
  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    environment:
      - APP_ENV=${APP_ENV:-production}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    networks:
      - laravel
    depends_on:
      - db

  webserver:
    build:
      context: ../
      dockerfile: ./docker/webserver/Dockerfile
    container_name: laravel_webserver
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ../public:/var/www/html/public
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ${DB_VOLUME:-dbdata}:/var/lib/mysql
    networks:
      - laravel

  npm:
    image: node:20-alpine
    container_name: npm_dev
    working_dir: /var/www/html
    command: ["npm", "run", "dev"]
    environment:
      - APP_ENV=${APP_ENV:-development}
    networks:
      - laravel
    volumes:
      - ../:/var/www/html:delegated
    depends_on:
      - app
    ports:
      - "5173:5173"

volumes:
  dbdata:
    driver: local
  prod_dbdata:
    driver: local
    driver_opts:
      type: none
      device: /mnt/docker-volumes/dbdata
      o: bind

networks:
  laravel:
    driver: bridge
